### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by dariusrosendahl**
- New npm scripts!
```
// create css only
"npm run create_css": "grunt create_css", 

//create html only
"npm run create_html": "grunt create_html",
 
//create js
"npm run create_js": "webpack", 

//create css, html and js
"npm run create_all": "npm run create_css & npm run create_html & npm run create_js & wait", 

//create everything and start browserSync server
"npm run start": "npm run create_js & grunt" 
```

- Removed all generated files from dist and added them to the gitignore
Files should always be generated as written in the documentation
- Updated the documentation with new npm scripts
- Updated devDependencies
- Version bumb to 1.3.0

### CODE REVIEW

**Comment by basmulderdnz** [comment]
"create_js" and "create_all" doesn't seem to be added in gruntfile.js and thus cannot be tested.

**Comment by dariusrosendahl** [comment]
@basmulderdnz It should be npm run {command}. I edited the original post.

**Comment by basmulderdnz** [comment]
@dariusrosendahl my bad. I do get an error on the 'wait' command during the 'npm run create_all' proces.
"'wait' is not recognized as an internal or external command, operable program or batch file."

The action does seem to be completed though.

**Comment by dariusrosendahl** [comment]
@basmulderdnz I removed the @wait command to avoid errors on Windows

**Review by basmulderdnz — APPROVED** [review]
Works like a charm

**Pull request merged**
